### ISSUE TITLE
support for play 2.4

### ISSUE THREAD

**Issue by pradeep122** [kenshoo/metrics-play#38] opened 2015-06-22 05:06 UTC
Current version of the library only supports play 2.3.

**Comment by lloydmeta** [comment] 2015-07-13 06:06
:+1:

**Comment by damirv** [comment] 2015-07-28 09:07
Is the support for 2.4 finished and published?

**Comment by liorhar** [comment] 2015-07-28 10:15
yep, docs updated, plugin was published http://mvnrepository.com/artifact/com.kenshoo/metrics-play_2.11/2.4.0_0.3.0

**Comment by sameergarg** [comment] 2015-07-29 16:17
Following the readme to add support for metrics in my application i am getting the following wrror when i access /admin/metrics url
```
! @6n1fb6ckh - Internal server error, for (GET) [/admin/metrics] ->
 
play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.kenshoo.play.metrics.MetricsController was bound.
  while locating com.kenshoo.play.metrics.MetricsController
    for parameter 3 at router.Routes.<init>(Routes.scala:35)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at scala.util.Success.flatMap(Try.scala:231) ~[scala-library-2.11.7.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.0.jar:2.4.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_45]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_45]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_45]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[na:1.8.0_45]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_45]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.kenshoo.play.metrics.MetricsController was bound.
  while locating com.kenshoo.play.metrics.MetricsController
    for parameter 3 at router.Routes.<init>(Routes.scala:35)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.Application$class.routes(Application.scala:111) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.DefaultApplication.routes(Application.scala:240) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.Play$.start(Play.scala:89) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156) ~[play-server_2.11-2.4.0.jar:2.4.0]
	... 14 common frames omitted
```

**Comment by gustavmauer** [comment] 2015-08-03 15:48
I am hitting the same error hitting any route after updating the routes file:

======================================
! @6n2pfd5i5 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.kenshoo.play.metrics.MetricsController was bound.
  while locating com.kenshoo.play.metrics.MetricsController
    for parameter 3 at router.Routes.<init>(Routes.scala:40)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.2.jar:2.4.2]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for com.kenshoo.play.metrics.MetricsController was bound.
  while locating com.kenshoo.play.metrics.MetricsController
    for parameter 3 at router.Routes.<init>(Routes.scala:40)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Application$class.routes(Application.scala:111) ~[play_2.11-2.4.2.jar:2.4.2]
======================================

This is a fairly simple Scala Play project created with "activator new".

I have added the library to build.sbt as follow:
libraryDependencies += "com.kenshoo" %% "metrics-play" % "2.4.0_0.3.0"

Then I have created conf/play.plugins and added:
1000:com.kenshoo.play.metrics.MetricsPlugin

I then added the "Default Registry" to a random action and nothing exploded when I accessed that action, but I do not know how to check if it worked.

Then when I updated the routes file, I get the error above.

**Comment by n3integration** [comment] 2015-08-04 14:33
+1

**Comment by breadfan** [comment] 2015-08-12 08:06
The problem is that play 2.4 with "routesGenerator := InjectedRoutesGenerator" in build.sbt expects the Controller to be a class, not an object as in the case of the Kenshoo Controller. I've got this working by doing the following:

1. Create your own controller CLASS
```
package controllers

import com.kenshoo.play.metrics.{MetricsRegistry, MetricsController => KenshooMetricsController}
import play.api.Play
import play.api.mvc.Controller

class MetricsController extends Controller with KenshooMetricsController {
  def registry = MetricsRegistry.defaultRegistry
  def app = Play.current
}
```
2. Use this in routes, instead of the one recommended in the readme:
```
GET        /admin/metrics                @controllers.MetricsController.metrics
```

**Comment by liorhar** [comment] 2015-10-18 12:33
#38 fixes the issue. version 2.4.0_0.4.1 supports it. closing.

**Closed by liorhar** 2015-10-18 12:34 UTC
